#!/bin/bash

ME=$(id -u)
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi

ACCT=$(whoami)

DPBX=Dropbox

	echo -e "\e[1;33m Welcome to Your Trucking Trans Solutions.\e[0m"
	echo -e "\e[1;33m One quick question \e[0m"
	echo -e "\e[1;33m whom am I loging in to.\e[0m"
	echo -e "\e[1;33mYTTS-admin ?.\e[0m"
	read varname
    echo -e "\e[1;36m $varname how are you on this $WDATE\e[0m"

if [ "$varname" = "$ACCT" ]; then
    echo -e "\e[1;36m Doing well I hope $ACCT  \e[0m"
    echo -e "\e[1;36m going to need youruser name and password\e[0m"
else 
	echo -e "\e[1;31m Sorry your name does not match the\e[0m"
	echo -e "\e[1;31m computer account login\e[0m"
	echo -e "\e[1;31m you will need to login \e[0m"
	echo -e "\e[1;31myour account try again.\e[0m"
	exit
fi

if su -c true "$USER"; then
  echo -e "\e[1;31m Correct password\e[0m"
else
    echo -e "\e[1;31m sorry User Name or Password does not match\e[0m"
    echo -e "\e[1;31m check your spelling caps on ?\e[0m"
    sleep 5
    exit
fi

echo -e "\e[1;33m your Dropbox is setup and running your github is setup and running? .\e[0m"
echo -e "\e[1;33m Example lower case! my-trucking-company no spaces on git hub .\e[0m"
printf '\e[38;2;255;0;0m  \n'
read -p 'the name of your git must match company name type it here lower case: ' repcomin
echo -e "\e[1;33m Example https://github.com/Drakeo/Youhas-trucking-test-scripts.git .\e[0m"
read -p 'the name of your git click clone and copy past it here : ' gitname
echo -e "\e[1;33m Upercase caps Best Trucking Company type BTC .\e[0m"
read -p 'company abriviations all caps sorts drivers Eample  Young Truckers Inc type in YTI  : ' coabriv


cat > sett <<EOF
sed -i 's/comin/$repcomin/g' YTTS-admin
sed -i 's/comin/$repcomin/g' YTTS-payroll
sed -i 's/comin/$repcomin/g' YTTS-rsync
sed -i 's/comin/$repcomin/g' YTTS-sort
sed -i 's/yourabrv/$coabriv/g' YTTS-admin
sed -i 's|githubaddres|$gitname|g' YTTS-rsync
EOF
sh sett
rm sett
echo -e "\e[1;33m Example lower case! my-trucking-company no spaces on git hub .\e[0m"
read -p 'wee need to setup your dropbox Ready? : ' decide
if [ "$decides" = "n" ]; then
   echo good day $ACCT
   exit
fi 
  
if [ "$decides" = "N" ]; then
   echo good day $ACCT
   exit
fi

read -p 'Name of your company ? : ' company
mkdir -p $HOME/$DPBX/$company
cd $HOME/$DPBX/$company
mkdir Customers  Deactivated  Drivers  Monthly  Saftey  Trailers  Trucks  Weekly  Yearly
#
