#!/bin/bash
ME=$(id -u)
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi
ACCT=$(whoami)
DATE=$(date +'%-1m-%d-%y')
WDATE=$(date +"%A")
SDRVBOL="split-DRV-bol-$DATE"
MDATE=$(date +'%-1m-%Y')
YDATE=$(date +'%Y')
# your company name
CPYNAME="comin"
DPBX=Dropbox
#begin YTTS-sort script
EMPLY="yourabrv-"

	echo -e "\e[1;33m Welcome to Your Trucking Trans Solutions.\e[0m"
	echo -e "\e[1;33m One quick question \e[0m"
	echo -e "\e[1;33m whom am I loging in to.\e[0m"
	echo -e "\e[1;33m YTTS-sort ?.\e[0m"
	read varname
    echo -e "\e[1;36m $varname how are you on this $WDATE\e[0m"

if [ "$varname" = "$ACCT" ]; then
    echo -e "\e[1;36m Doing well I hope $ACCT  \e[0m"
    echo -e "\e[1;36m going to need your YTTS-sort login and password\e[0m"
else 
	echo -e "\e[1;31m Sorry your name does not match the\e[0m"
	echo -e "\e[1;31m computer account login\e[0m"
	echo -e "\e[1;31m you will need to login \e[0m"
	echo -e "\e[1;31myour account try again.\e[0m"
	exit
fi

if su -c true "$USER"; then
  echo -e "\e[1;31m Correct password\e[0m"
else
    echo -e "\e[1;31m sorry User Name or Password does not match\e[0m"
    echo -e "\e[1;31m check your spelling caps on ?\e[0m"
    sleep 5
    exit
fi


read -p ' YTTS-splits should be done any time to be sorted ? Y/N : ' decides

if [ "$decides" = "n" ]; then
   echo good day $ACCT
   exit
fi 
  
if [ "$decides" = "N" ]; then
   echo good day $ACCT
   exit
fi

cd $HOME/$DPBX/$CPYNAME/Drivers
if [ -d $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL ]; then
cp *$EMPLY*/split-*.jpg $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
cp *$EMPLY*/split-*.jpeg $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
cp *$EMPLY*/split-*.png $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
cp *$EMPLY*/split-*.pdf $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
else
mkdir -p $SDRVBOL
cp *$EMPLY*/split-*.jpg $SDRVBOL
cp *$EMPLY*/split-*.jpeg $SDRVBOL
cp *$EMPLY*/split-*.png $SDRVBOL
cp *$EMPLY*/split-*.pdf $SDRVBOL 
mv $HOME/$DPBX/$CPYNAME/Drivers/$SDRVBOL  $HOME/$DPBX/$CPYNAME/Splits/
fi
YTTS-rsync
