#!/bin/bash
ME=$(id -u)
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi
ACCT=$(whoami)
DATE=$(date +'%-1m-%d-%y')
WDATE=$(date +"%A")
DRECPT="DRV-receipts-$DATE"
DRVBOL="DRV-bol-$DATE"
MDATE=$(date +'%-1m-%Y')
YDATE=$(date +'%Y')
MDRECPT="DRV-receipts-$MDATE"
MDRVBOL="DRV-bol-$MDATE"
YDRECPT="DRV-receipts-$YDATE"
YDRVBOL="DRV-bol-$YDATE"
CPYNAME="comin"
DPBX=Dropbox
EMPLY="yourabrv-"
#begin YTTS-sort script

	echo -e "\e[1;33m Welcome to Your Trucking Trans Solutions.\e[0m"
	echo -e "\e[1;33m One quick question \e[0m"
	echo -e "\e[1;33m whom am I loging in to.\e[0m"
	echo -e "\e[1;33m YTTS-sort ?.\e[0m"
	read varname
    echo -e "\e[1;36m $varname how are you on this $WDATE\e[0m"

if [ "$varname" = "$ACCT" ]; then
    echo -e "\e[1;36m Doing well I hope $ACCT  \e[0m"
    echo -e "\e[1;36m going to need your YTTS-sort login and password\e[0m"
else 
	echo -e "\e[1;31m Sorry your name does not match the\e[0m"
	echo -e "\e[1;31m computer account login\e[0m"
	echo -e "\e[1;31m you will need to login \e[0m"
	echo -e "\e[1;31myour account try again.\e[0m"
	exit
fi

if su -c true "$USER"; then
  echo -e "\e[1;31m Correct password\e[0m"
else
    echo -e "\e[1;31m sorry User Name or Password does not match\e[0m"
    echo -e "\e[1;31m check your spelling caps on ?\e[0m"
    sleep 5
    exit
fi


read -p ' YTTS-sort should be done any time to pull bills from drivers account for billing ? Y/N : ' decides

if [ "$decides" = "n" ]; then
   echo good day $ACCT
   exit
fi 
  
if [ "$decides" = "N" ]; then
   echo good day $ACCT
   exit
fi

cd $HOME/$DPBX/$CPYNAME/Drivers
if [ -d $HOME/$DPBX/$CPYNAME/Weekly/$DRECPT ]; then
cp */Receipts/*.jpg $HOME/$DPBX/$CPYNAME/Weekly/$DRECPT
cp */Receipts/*.jpeg $HOME/$DPBX/$CPYNAME/Weekly/$DRECPT
cp */Receipts/*.png $HOME/$DPBX/$CPYNAME/Weekly/$DRECPT
cp */Receipts/*.pdf $HOME/$DPBX/$CPYNAME/Weekly/$DRECPT
else
mkdir -p $HOME/$DPBX/$CPYNAME/Drivers/$DRECPT
cp */Receipts/*.jpg $DRECPT
cp */Receipts/*.jpeg $DRECPT
cp */Receipts/*.png $DRECPT
cp */Receipts/*.pdf $DRECPT
mv $HOME/$DPBX/$CPYNAME/Drivers/$DRECPT $HOME/$DPBX/$CPYNAME/Weekly/
fi

if [ -d $HOME/$DPBX/$CPYNAME/Weekly/$DRVBOL ]; then
cp *$EMPLY*/*.jpg $HOME/$DPBX/$CPYNAME/Weekly/$DRVBOL 
cp *$EMPLY*/*.jpeg $HOME/$DPBX/$CPYNAME/Weekly/$DRVBOL 
cp *$EMPLY*/*.png $HOME/$DPBX/$CPYNAME/Weekly/$DRVBOL 
cp *$EMPLY*/*.pdf $HOME/$DPBX/$CPYNAME/Weekly/$DRVBOL 
else
mkdir -p $DRVBOL
cp *$EMPLY*/*.jpg $DRVBOL
cp *$EMPLY*/*.jpeg $DRVBOL
cp *$EMPLY*/*.png $DRVBOL
cp *$EMPLY*/*.pdf $DRVBOL 
mv $HOME/$DPBX/$CPYNAME/Drivers/$DRVBOL  $HOME/$DPBX/$CPYNAME/Weekly/
fi
#start monthly
cd $HOME/$DPBX/$CPYNAME/Weekly/

if [ -d $HOME/$DPBX/$CPYNAME/Monthly/$MDRECPT ]; then
cp DRV-receipts-*/*.jpg $HOME/$DPBX/$CPYNAME/Monthly/$MDRECPT
cp DRV-receipts-*/*.jpeg $HOME/$DPBX/$CPYNAME/Monthly/$MDRECPT
cp DRV-receipts-*/*.png $HOME/$DPBX/$CPYNAME/Monthly/$MDRECPT
cp DRV-receipts-*/*.pdf $HOME/$DPBX/$CPYNAME/Monthly/$MDRECPT
else
mkdir -p $MDRECPT
cp DRV-receipts-*/*.jpg $MDRECPT
cp DRV-receipts-*/*.jpeg $MDRECPT
cp DRV-receipts-*/*.png $MDRECPT
cp DRV-receipts-*/*.pdf $MDRECPT
mv $HOME/$DPBX/$CPYNAME/Weekly/$MDRECPT $HOME/$DPBX/$CPYNAME/Monthly/
fi

if [ -d $HOME/$DPBX/$CPYNAME/Monthly/$MDRVBOL ]; then
cp DRV-bol-*/*.jpg $HOME/$DPBX/$CPYNAME/Monthly/$MDRVBOL
cp DRV-bol-*/*.jpeg $HOME/$DPBX/$CPYNAME/Monthly/$MDRVBOL
cp DRV-bol-*/*.png $HOME/$DPBX/$CPYNAME/Monthly/$MDRVBOL
cp DRV-bol-*/*.pdf $HOME/$DPBX/$CPYNAME/Monthly/$MDRVBOL
else
mkdir -p $MDRVBOL
cp DRV-bol-*/*.jpg $MDRVBOL
cp DRV-bol-*/*.jpeg $MDRVBOL
cp DRV-bol-*/*.png $MDRVBOL
cp DRV-bol-*/*.pdf $MDRVBOL
mv $HOME/$DPBX/$CPYNAME/Weekly/$MDRVBOL $HOME/$DPBX/$CPYNAME/Monthly/
fi
#anual
cd $HOME/$DPBX/$CPYNAME/Monthly/

if [ -d $HOME/$DPBX/$CPYNAME/Yearly/$YDRECPT ]; then
cp DRV-receipts-*/*.jpg $HOME/$DPBX/$CPYNAME/Yearly/$YDRECPT
cp DRV-receipts-*/*.jpeg $HOME/$DPBX/$CPYNAME/Yearly/$YDRECPT
cp DRV-receipts-*/*.png $HOME/$DPBX/$CPYNAME/Yearly/$YDRECPT
cp DRV-receipts-*/*.pdf $HOME/$DPBX/$CPYNAME/Yearly/$YDRECPT
else
mkdir -p $YDRECPT
cp DRV-receipts-*/*.jpg $YDRECPT
cp DRV-receipts-*/*.jpeg $YDRECPT
cp DRV-receipts-*/*.png $YDRECPT
cp DRV-receipts-*/*.pdf $YDRECPT
mv $HOME/$DPBX/$CPYNAME/Monthly/$YDRECPT $HOME/$DPBX/$CPYNAME/Yearly/
fi
# anual 
if [ -d $HOME/$DPBX/$CPYNAME/Yearly/$YDRVBOL ]; then
cp DRV-bol-*/*.jpg $HOME/$DPBX/$CPYNAME/Yearly/$YDRVBOL
cp DRV-bol-*/*.jpeg $HOME/$DPBX/$CPYNAME/Yearly/$YDRVBOL
cp DRV-bol-*/*.png $HOME/$DPBX/$CPYNAME/Yearly/$YDRVBOL
cp DRV-bol-*/*.pdf $HOME/$DPBX/$CPYNAME/Yearly/$YDRVBOL
else
mkdir -p $YDRVBOL
cp DRV-bol-*/*.jpg $YDRVBOL
cp DRV-bol-*/*.jpeg $YDRVBOL
cp DRV-bol-*/*.png $YDRVBOL
cp DRV-bol-*/*.pdf $YDRVBOL
mv $HOME/$DPBX/$CPYNAME/Monthly/$YDRVBOL $HOME/$DPBX/$CPYNAME/Yearly/
fi
echo -e "\e[1;33m daily weekly monthly have been created\e[0m"
echo -e "\e[1;33m ok going to comit changes.\e[0m"
echo -e "\e[1;32m pause 3 seconds to read this\e[0m"
sleep 3
sh $HOME/YTTS/bin/YTTS-rsync


