#!/bin/bash
ME=$(id -u)
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi
ACCT=$(whoami)
DATE=$(date +'%-1m-%d-%y')
WDATE=$(date +"%A")
SDRVBOL="split-DRV-bol-$DATE"
MDATE=$(date +'%-1m-%Y')
YDATE=$(date +'%Y')
# your company name
CPYNAME="comin"
DPBX=Dropbox
#begin YTTS-sort script
EMPLY="yourabrv-"

	echo Welcome to Your Trucking Trans Solutions.



read -p ' YTTS-splits should be done any time to be sorted ? Y/N : ' decides

if [ "$decides" = "n" ]; then
   echo good day $ACCT
   exit
fi 
  
if [ "$decides" = "N" ]; then
   echo good day $ACCT
   exit
fi

cd $HOME/$DPBX/$CPYNAME/Drivers
if [ -d $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL ]; then
cp *$EMPLY*/split-*.jpg $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
cp *$EMPLY*/split-*.jpeg $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
cp *$EMPLY*/split-*.png $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
cp *$EMPLY*/split-*.pdf $HOME/$DPBX/$CPYNAME/Splits/$SDRVBOL 
else
mkdir -p $SDRVBOL
cp *$EMPLY*/split-*.jpg $SDRVBOL
cp *$EMPLY*/split-*.jpeg $SDRVBOL
cp *$EMPLY*/split-*.png $SDRVBOL
cp *$EMPLY*/split-*.pdf $SDRVBOL 
mv $HOME/$DPBX/$CPYNAME/Drivers/$SDRVBOL  $HOME/$DPBX/$CPYNAME/Splits/
fi
sh $HOME/YTTS/bin/YTTS-rsync
