#!/bin/bash


if [ -d $HOME/Youhas-trucking-test-scripts ]; then
cd $HOME/Youhas-trucking-test-scripts
  git checkout master 
  git pull
cd $HOME
else
cd $HOME
  git clone https://github.com/Drakeo/Youhas-trucking-test-scripts.git
fi
echo make backup of dropbox
sleep 3
rsync -r -a -v  --progress --stats --exclude .git $HOME/Dropbox/ Dropbox-bkp/
rsync -r -a -v  --delete --progress --stats --exclude .git --exclude .gitignore  \
  --exclude YTTS-admin  --exclude  YTTS-rsync  --exclude  YTTS-sort --exclude YTTS-payroll \
 $HOME/Dropbox/  $HOME/Youhas-trucking-test-scripts/

echo ok going to comit changes

cat > gitadd <<EOF
cd $HOME/Youhas-trucking-test-scripts 
git add -A
git commit -a -m 'upload`date +%s`'
git push
EOF
sh gitadd
rm gitadd
echo check your https://github.com/Drakeo/Youhas-trucking-test-scripts.git
echo  all updated
sleep 5
