#!/bin/bash

ME=$(id -u)
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi

ACCT=$(whoami)

DPBX=Dropbox
DESK="$HOME/.local/share/YTTS/bin"
ICON="$HOME/.local/share/YTTS/icons"

	echo -e "\e[1;33m Welcome to Your Trucking Trans Solutions.\e[0m"
	echo -e "\e[1;33m One quick question \e[0m"
	echo -e "\e[1;33m whom am I loging in to.\e[0m"
	echo -e "\e[1;33mYTTS-setup ?.\e[0m"
	read varname
    echo -e "\e[1;36m $varname how are you on this $WDATE\e[0m"

if [ "$varname" = "$ACCT" ]; then
    echo -e "\e[1;36m Doing well I hope $ACCT  \e[0m"
    echo -e "\e[1;36m going to need youruser name and password\e[0m"
else 
	echo -e "\e[1;31m Sorry your name does not match the\e[0m"
	echo -e "\e[1;31m computer account login\e[0m"
	echo -e "\e[1;31m you will need to login \e[0m"
	echo -e "\e[1;31myour account try again.\e[0m"
	exit
fi

if su -c true "$USER"; then
  echo -e "\e[1;31m Correct password\e[0m"
else
    echo -e "\e[1;31m sorry User Name or Password does not match\e[0m"
    echo -e "\e[1;31m check your spelling caps on ?\e[0m"
    sleep 5
    exit
fi


printf '\e[38;2;255;0;0m  \n'
read -p 'the name of your company: ' repcomin
echo -e "\e[1;33m Example https://github.com/Drakeo/demo-trucking-company.git .\e[0m"
read -p 'the name of your git-hub click clone and copy past it here : ' gitname
echo -e "\e[1;33m the actual name of the github  example demo-trucking-company .\e[0m"
read -p 'the actual name of the github  : ' gitlittle
echo -e "\e[1;33m Upercase caps Best Trucking Company type BTC .\e[0m"
read -p 'company abriviations all caps sorts drivers Eample  Young Truckers Inc type in DTC  : ' coabriv
read -p 'company address   : ' address
read -p 'company phone number   : ' phone



cat > sett <<EOF
sed -i 's/comin/$repcomin/g' YTTS-admin
sed -i 's/comin/$repcomin/g' YTTS-customer-sort
sed -i 's/comin/$repcomin/g' YTTS-payroll
sed -i 's/comin/$repcomin/g' YTTS-rsync
sed -i 's/comin/$repcomin/g' YTTS-sort
sed -i 's/yourabrv/$coabriv/g' YTTS-admin
sed -i 's/yourabrv/$coabriv/g' YTTS-sort
sed -i 's/comin/$repcomin/g' YTTS-split
sed -i 's/yourabrv/$coabriv/g' YTTS-split
sed -i 's|githubaddres|$gitname|g' YTTS-rsync
sed -i 's/ADDME/$address/g' YTTS-admin
sed -i 's/PHONME/$phone/g' YTTS-admin
sed -i 's|gitshort|$gitlittle|g' YTTS-rsync
EOF
sh sett
rm sett
cd $HOME/.local/share/applications
cat > dsett <<EOF
sed -i 's|Exec=|Exec=$DESK|g' YTTS-admin.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-payroll.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-rsync.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-sort.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-split.desktop
sed -i 's|Exec=|Exec=$DESK|g' YTTS-customer-sort.desktop  
sed -i 's|Icon=|Icon=$ICON|g' YTTS-admin.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-payroll.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-rsync.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-sort.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-split.desktop
sed -i 's|Icon=|Icon=$ICON|g' YTTS-customer-sort.desktop  
EOF
sh dsett
rm dsett


read -p 'Do you need to setup your dropbox Ready Y/N : ' decides
if [ "$decides" = "n" ]; then
   echo good day $ACCT
   exit
fi 
  
if [ "$decides" = "N" ]; then
   echo good day $ACCT
   exit
fi


mkdir -p $HOME/$DPBX/$repcomin
cd $HOME/$DPBX/$repcomin
mkdir Customers  Deactivated  Drivers  Monthly  Saftey Splits Trailers  Trucks  Weekly  Yearly
cd Deactivated 
mkdir Deactivated-Trailers Deactivated-Trucks Deactivated-Drivers
#

 
