#!/bin/bash
ME=$(id -u)
#Github name = company name
CPYNAME="comin"
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi
read -p '!! Do you need to update Dropbox from Android   Y/N : ' decides
if [ "$decides" = "n" ]; then
   echo Ok $ACCT
fi 
  
if [ "$decides" = "N" ]; then
   echo Ok $ACCT
fi
if [ "$decides" = "y" ]; then
   rsync -r -a -v  --delete --progress --stats --exclude .git --exclude .gitignore  \
   $HOME/gitshort $HOME/Dropbox/comin/ 
      read -p 'push enter create any new links or share in Dropbox: ' hope
    firefox https://www.dropbox.com/home/$CPYNAME
    exit 
fi 
  
if [ "$decides" = "Y" ]; then
   rsync -r -a -v  --delete --progress --stats --exclude .git --exclude .gitignore  \
   $HOME/gitshort $HOME/Dropbox/comin/
   read -p 'push enter create any new links or share in Dropbox: ' hope
   firefox https://www.dropbox.com/home/$CPYNAME 
   exit 
fi
#Github name = company name

if [ -d $HOME/$CPYNAME ]; then
cd $HOME/$CPYNAME 
  git checkout master 
  git pull
cd $HOME
else
cd $HOME
  git clone githubaddres
fi
echo make backup of dropbox
sleep 3
rsync -r -a -v  --progress --stats --exclude .git $HOME/Dropbox/ Dropbox-bkp/
rsync -r -a -v  --delete --progress --stats --exclude .git --exclude .gitignore  \
 $HOME/Dropbox/comin  $HOME/gitshort/

echo ok going to comit changes

cat > gitadd <<EOF
cd $HOME/comin
git add -A
git commit -a -m 'upload`date +%s`'
git push
EOF
sh gitadd
rm gitadd
echo check your githubaddres
echo  all updated
sleep 5
